### ISSUE TITLE
Demo link dead

### ISSUE THREAD

**Issue by funkytaco** [webRTC-io/webrtc.io-demo#16]
Demo link to http://107.20.223.140/ no longer works.

**Comment by dennismartensson** [comment]
http://webrtc.dennis.is/

**Comment by sarenji** [comment]
@dennismartensson Please update the link in the README.

**Comment by dennismartensson** [comment]
I will do that. Sorry for taking so long

**Comment by dennismartensson** [comment]
I have now commited the demo running on webrtc.dennis.is
