### ISSUE TITLE
double .src=url in the example

### ISSUE THREAD

**Issue by jeromeetienne** [webRTC-io/webrtc.io-demo#4]
in https://github.com/webRTC/webrtc.io-demo/blob/master/example/index.html#L160

you can see the following

```
          rtc.createStream({"video": true, "audio": true}, function(stream) {
            document.getElementById('you').src = URL.createObjectURL(stream);
            rtc.attachStream(stream, 'you');
          });
```

and in https://github.com/webRTC/webrtc.io-client/blob/master/lib/webrtc.io.js `.attachStream` is 

```
    rtc.attachStream = function(stream, domId) {
      document.getElementById(domId).src = URL.createObjectURL(stream);
    };
```

so this `.src= url` is done twice

**Comment by dennismartensson** [comment]
This do look like a good fix. Can you please submit a pull request?

**Comment by danielkutik** [comment]
This issue can be closed.
