### ISSUE TITLE
Error:Cannot find module "ws"

### ISSUE THREAD

**Issue by Abendstern** [webRTC-io/webrtc.io-demo#5]
Hi,
I tried to install the application just like the description but i am receiving this error

Run in your terminal

git clone git@github.com:dennismartensson/webrtc.io-demo.git
cd webrtc.io-demo
npm install
cd example
node server.js

When i wrote the last command, it gives an error. Inside the \node_modules\webrtc.io\lib\webrtc.io.js:2:23

**Comment by dennismartensson** [comment]
You are using the wrong repository!

as you can se here https://github.com/webRTC/webrtc.io-demo

git clone git@github.com:webRTC/webrtc.io-demo.git
cd webrtc.io-demo
npm install
cd example
node server.js

**Comment by redflasher** [comment]
Abendstern, you must add _CLIENT_VERSION_ webrtc.io.js into example/.
look it here: https://github.com/webRTC/webrtc.io-client
